### ISSUE TITLE
Peak Map Cannot Display Lines Below Sea Level

### ISSUE THREAD

**Issue by corvanessen** [anvaka/peak-map#3]
When looking at the map of the Netherlands it can be seen that locations below sea level are no displayed on the Peak map.
Expected behavior: land that is below sea level is still visible.

**Comment by anvaka** [comment]
The tool cuts off line rendering when elevation is below ocean level. You can adjust the cut off value by changing where ocean level is. Here is a demo: https://imgur.com/a/hj96Qbn
